# Generated by Django 5.0.7 on 2024-07-31 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_prettynum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='管理员')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
    ]
